SELECT TOP (1000) [id]
      ,[empresa_id]
      ,[titulo]
      ,[descripcion]
      ,[requisitos]
      ,[ubicacion]
      ,[salario]
      ,[tipo]
      ,[fecha_publicacion]
      ,[activo]
  FROM [web_trabajo].[dbo].[empleos]
